
services:
  catalog-db:
    image: postgres

  order-db:
    image: mcr.microsoft.com/mssql/server

  distributedcache:
    image: redis

  basket-db:
    image: postgres

  messagebroker:
    image: rabbitmq:management

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}ordering.api
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigatway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGatway/Dockerfile

  shopping.web:
    image: ${DOCKER_REGISTRY-}shopping.web
    build:
      context: .
      dockerfile: WebApps/Shopping.Web/Dockerfile

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

volumes:
  postgres_catalog:
  postgres_basket:
  pgadmin_data:
  portainer_data:
  elasticsearch_data:
    driver: local

